### ISSUE TITLE
Replace Yabause with Mednafen Saturn

### ISSUE THREAD

**Issue by RobLoach** [escalade/LibreELEC.tv#3]
[beetle-saturn-libretro](https://github.com/libretro/beetle-saturn-libretro) is a much improved core over [yabause](https://github.com/libretro/yabause). Mednafen's Saturn support is a lot better in that it loads .cue files correctly, and is much more up to date with the latest in Saturn emulation. While it is still young, it has come much further then Yabause.

Here's a couple demos of it:
- https://www.youtube.com/watch?v=Slq1dgdvyjo
- https://www.youtube.com/watch?v=Jxv62yvJBfY

PS, this fork continuously impresses me :+1: .... Are you on #libretro IRC at all? https://github.com/libretro/RetroArch#support

**Comment by escalade** [comment]
I've noticed it, I do keep an eye on github.com/libretro to watch any interesting change in the cores. I'll have a look at your PR and merge it. Don't use sega saturn myself but I'll include it if it's an improvement over yabause.

I'm not present on any IRC channels, but I hang out on LE slack sometimes. I started this fork mostly to learn git more and because I wasn't happy about the slow Lakka development pace. Also it's a shame to have a powerful HTPC only to run Kodi on it. Happy that you like it :)
